/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/api-client.ts
var HabiticaApiClient = class {
  /**
   * @param apiUser  Habitica account user ID (UUID). Sent as `x-api-user` header.
   * @param apiToken Habitica API token. Sent as `x-api-key` header.
   */
  constructor(apiUser, apiToken) {
    this.apiUser = apiUser;
    this.apiToken = apiToken;
    this.baseUrl = "https://habitica.com/api/v3";
    this.headers = {
      "x-api-user": apiUser,
      "x-api-key": apiToken,
      "x-client": "habitica-fullsync-js",
      "Content-Type": "application/json"
    };
  }
  /**
   * Wraps `fetch` with automatic retry on HTTP 429 (rate limited) using exponential backoff.
   *
   * On a 429 response, reads the `X-RateLimit-Reset` header (seconds until reset) and waits
   * that long before retrying. If the header is absent, falls back to the current `delay`.
   * `delay` doubles after each 429.
   *
   * @param url     Absolute URL to request.
   * @param options Standard `RequestInit` options forwarded to `fetch`.
   * @param retries Maximum total attempts before giving up. Defaults to `3`.
   * @param delay   Initial backoff in milliseconds, doubles on each 429. Defaults to `1000`.
   * @returns The raw `Response` for the first non-429 reply.
   * @throws {Error} When all retries are exhausted.
   */
  async rateLimitedFetch(url, options = {}, retries = 3, delay = 1e3) {
    for (let i = 0; i < retries; i++) {
      const res = await fetch(url, options);
      if (res.status === 429) {
        const resetHeader = res.headers.get("X-RateLimit-Reset");
        const resetParsed = resetHeader ? parseInt(resetHeader, 10) : NaN;
        const reset = Number.isFinite(resetParsed) ? resetParsed : Math.ceil(delay / 1e3);
        await new Promise((resolve) => setTimeout(resolve, reset * 1e3));
        delay *= 2;
        continue;
      }
      return res;
    }
    throw new Error("Max retries reached for " + url);
  }
  /**
   * Validates an API `Response` and extracts the `data` payload from the Habitica envelope.
   *
   * Checks in order:
   * 1. `res.ok` — throws on any non-2xx HTTP status, including up to 200 chars of the body.
   * 2. JSON parseability — throws if `res.json()` rejects.
   * 3. `json.success === false` — throws with `json.message` on application-level errors.
   *
   * @param res     The raw `Response` from {@link rateLimitedFetch}.
   * @param context Human-readable label in error messages (e.g. `'fetchUserTasks'`).
   * @returns `json.data` cast to `T`.
   * @throws {Error} On HTTP error, parse failure, or Habitica application error.
   */
  async _parseResponse(res, context) {
    if (!res.ok) {
      let body = "";
      try {
        body = await res.text();
      } catch (_) {
      }
      throw new Error(`Habitica API error [${context}]: HTTP ${res.status} \u2014 ${body.slice(0, 200)}`);
    }
    let json;
    try {
      json = await res.json();
    } catch (e) {
      throw new Error(`Habitica API error [${context}]: invalid JSON response`);
    }
    if (json.success === false) {
      throw new Error(`Habitica API error [${context}]: ${json.message || "unknown error"}`);
    }
    return json.data;
  }
  /**
   * Fetches all tasks belonging to the authenticated user.
   * Calls `GET /api/v3/tasks/user`.
   * @throws {Error} On network failure, HTTP error, or Habitica application error.
   */
  async fetchUserTasks() {
    const res = await this.rateLimitedFetch(`${this.baseUrl}/tasks/user`, { headers: this.headers });
    return this._parseResponse(res, "fetchUserTasks");
  }
  /**
   * Fetches all tags belonging to the authenticated user.
   * Calls `GET /api/v3/tags`. Used to build a tag-lookup map (`id → name`) for task formatting.
   * @throws {Error} On network failure, HTTP error, or Habitica application error.
   */
  async fetchTags() {
    const res = await this.rateLimitedFetch(`${this.baseUrl}/tags`, { headers: this.headers });
    return this._parseResponse(res, "fetchTags");
  }
  /**
   * Fetches all tasks belonging to a Habitica group (party or guild).
   * Calls `GET /api/v3/tasks/group/:groupId`.
   * @param groupId UUID of the Habitica group.
   * @throws {Error} On network failure, HTTP error, or Habitica application error.
   */
  async fetchGroupTasks(groupId) {
    const res = await this.rateLimitedFetch(`${this.baseUrl}/tasks/group/${groupId}`, { headers: this.headers });
    return this._parseResponse(res, "fetchGroupTasks");
  }
  /**
   * Creates a new task in Habitica.
   * Calls `POST /api/v3/tasks/user`. Only fields present in `input` are sent.
   *
   * @param input Task fields. `text` and `type` are required; `priority`, `date`,
   *              `startDate`, `frequency`, `tags`, and `notes` are optional. Habits default
   *              to `up: true` / `down: false`.
   * @returns The newly created task, including the server-assigned `id`.
   * @throws {Error} On network failure, HTTP error, or Habitica application error.
   */
  async createTask(input) {
    const body = { text: input.text, type: input.type };
    if (input.notes)
      body.notes = input.notes;
    else
      body.notes = "Created from Obsidian";
    if (typeof input.priority === "number")
      body.priority = input.priority;
    if (input.date)
      body.date = input.date;
    if (input.startDate)
      body.startDate = input.startDate;
    if (input.frequency)
      body.frequency = input.frequency;
    if (Array.isArray(input.tags) && input.tags.length)
      body.tags = input.tags;
    if (input.type === "habit") {
      body.up = true;
      body.down = false;
    }
    const res = await this.rateLimitedFetch(`${this.baseUrl}/tasks/user`, {
      method: "POST",
      headers: this.headers,
      body: JSON.stringify(body)
    });
    return this._parseResponse(res, "createTask");
  }
  /**
   * Creates a new tag in Habitica.
   * Calls `POST /api/v3/tags`.
   * @param name Display name of the tag.
   * @returns The newly created tag, including the server-assigned `id`.
   * @throws {Error} On network failure, HTTP error, or Habitica application error.
   */
  async createTag(name) {
    const res = await this.rateLimitedFetch(`${this.baseUrl}/tags`, {
      method: "POST",
      headers: this.headers,
      body: JSON.stringify({ name })
    });
    return this._parseResponse(res, "createTag");
  }
  /**
   * Adds a checklist (subtask) item to an existing task.
   * Calls `POST /api/v3/tasks/:taskId/checklist`.
   * @param taskId UUID of the parent task.
   * @param text   Display text of the checklist item.
   * @returns The updated parent task, including the full `checklist` array.
   * @throws {Error} On network failure, HTTP error, or Habitica application error.
   */
  async addChecklistItem(taskId, text) {
    const res = await this.rateLimitedFetch(`${this.baseUrl}/tasks/${taskId}/checklist`, {
      method: "POST",
      headers: this.headers,
      body: JSON.stringify({ text })
    });
    return this._parseResponse(res, `addChecklistItem/${taskId}`);
  }
  /**
   * Scores (completes or increments) a task in Habitica.
   * Calls `POST /api/v3/tasks/:id/score/:direction`.
   * @param id        UUID of the task to score.
   * @param direction `'up'` for positive scoring; `'down'` for negative (habits only).
   * @returns The raw score delta response (HP/XP/gold changes). Typed as `unknown` because
   *          the shape varies by task type and is not consumed by the plugin.
   * @throws {Error} On network failure, HTTP error, or Habitica application error.
   */
  async scoreTask(id, direction) {
    const res = await this.rateLimitedFetch(`${this.baseUrl}/tasks/${id}/score/${direction}`, {
      method: "POST",
      headers: this.headers
    });
    return this._parseResponse(res, `scoreTask/${id}`);
  }
};

// src/vault-handler.ts
function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
var VaultHandler = class {
  /** @param app The Obsidian application instance. Provides vault and file-system access. */
  constructor(app) {
    this.app = app;
  }
  /**
   * Scans all Markdown files modified on or after `cutoffDate` for completed tasks not yet scored.
   *
   * A task qualifies if:
   * 1. Its file `mtime` ≥ `cutoffDate`.
   * 2. The line starts with `- [x]`.
   * 3. The line does NOT contain `%%scored%%`.
   * 4. The line has a `[completion:: YYYY-MM-DD]` field with a date ≥ `cutoffDate`.
   *
   * @param cutoffDate Earliest date to consider (tasks and files older than this are skipped).
   * @returns Array of `{ line, file }` pairs for each qualifying task.
   */
  async getRecentCompletedTasks(cutoffDate) {
    const completedTasks = [];
    for (const file of this.app.vault.getMarkdownFiles()) {
      if (file.stat.mtime < cutoffDate.getTime())
        continue;
      const content = await this.app.vault.read(file);
      for (const line of content.split("\n")) {
        if (!line.startsWith("- [x]"))
          continue;
        if (line.includes("%%scored%%"))
          continue;
        const completionMatch = line.match(/\[completion:: (\d{4}-\d{2}-\d{2})\]/);
        if (!completionMatch)
          continue;
        const completionDate = new Date(completionMatch[1]);
        if (completionDate >= cutoffDate) {
          completedTasks.push({ line, file });
        }
      }
    }
    return completedTasks;
  }
  /**
   * Replaces an existing task line in a vault file with an updated version.
   *
   * Uses a three-strategy cascade to locate the target line:
   *
   * **Strategy 1 — ID match (preferred):** If `newLine` contains `[id:: <id>]`, searches for
   * any line in the file containing the same ID token. Stable and collision-proof.
   *
   * **Strategy 2 — Prefix-regex fallback:** Extracts the text before the first ` [id::` in
   * `newLine` and matches it as a prefix pattern. Used when the ID is not yet in the file.
   *
   * **Strategy 3 — Warning only:** If neither strategy matches, logs a warning without
   * modifying the file. Prevents silent data corruption.
   *
   * @param file    The vault file to update.
   * @param newLine The complete replacement line, including any new annotations like `%%scored%%`.
   */
  async updateLine(file, newLine) {
    const content = await this.app.vault.read(file);
    const idMatch = newLine.match(/\[id:: ([^\]]+)\]/);
    if (idMatch) {
      const id = idMatch[1];
      const idPattern = new RegExp(`^[^
]*\\[id:: ${escapeRegExp(id)}\\][^
]*$`, "m");
      if (idPattern.test(content)) {
        const updated = content.replace(idPattern, newLine);
        await this.app.vault.modify(file, updated);
        return;
      }
    }
    const prefix = newLine.split(" [id::")[0];
    const prefixPattern = new RegExp(`^${escapeRegExp(prefix)}.*$`, "m");
    if (prefixPattern.test(content)) {
      const updated = content.replace(prefixPattern, newLine);
      await this.app.vault.modify(file, updated);
      return;
    }
    console.warn(`habitica-fullsync VaultHandler.updateLine: could not locate target line in "${file.path}". Line was:
${newLine}`);
  }
  /**
   * Scans a single vault file for checked-off task lines with a Habitica ID that have
   * not yet been marked `%%scored%%`. Used to detect tasks the user marks complete
   * directly in the sync output file (`habitica-fullsync.md`).
   *
   * Only `todo` and `daily` task lines are safe to score via this path because:
   * - Habitica marks them `completed: true` after scoring, making them idempotent.
   * - Habits never become `completed: true`, so they would be re-scored on every sync
   *   until the file is regenerated.
   *
   * @param filePath Vault-relative path to the sync output file.
   * @returns Array of `{ id, line }` for each qualifying task, deduplicated by ID.
   */
  async getCheckedTasksFromFile(filePath) {
    try {
      const content = await this.app.vault.adapter.read(filePath);
      const seen = /* @__PURE__ */ new Set();
      const results = [];
      for (const line of content.split("\n")) {
        if (!line.startsWith("- [x]"))
          continue;
        if (line.includes("%%scored%%"))
          continue;
        const idMatch = line.match(/\[id:: ([^\]]+)\]/);
        if (idMatch && !seen.has(idMatch[1])) {
          seen.add(idMatch[1]);
          results.push({ id: idMatch[1], line });
        }
      }
      return results;
    } catch (_) {
      return [];
    }
  }
  /**
   * Scans a single vault file for hand-written task lines eligible to be created in Habitica.
   *
   * A line qualifies if it is a top-level (non-indented) `- [ ]` line that:
   * - has **no** `[id:: ...]` field (not yet a managed task),
   * - is not the `_No tasks found._` placeholder.
   *
   * The current `### ` level-3 heading is tracked as the line's `section` (used to infer task
   * type). Lines inside a `#### Group Tasks` subsection are **skipped** — group-task creation is
   * not supported and would otherwise create a personal task. Any following nested `> [!note]`
   * callout lines and nested `  - [ ]` checklist lines are gathered with the task.
   *
   * @param filePath Vault-relative path to the sync output file.
   * @returns Array of `{ line, section, notes, checklistTexts }`. Never throws — returns `[]`
   *          if the file does not exist yet.
   */
  async getCreatableLinesFromFile(filePath) {
    try {
      const content = await this.app.vault.adapter.read(filePath);
      const lines = content.split("\n");
      const results = [];
      let section = "";
      let inGroupSubsection = false;
      for (let i = 0; i < lines.length; i++) {
        const raw = lines[i];
        const h3 = raw.match(/^### (.+)$/);
        if (h3) {
          section = h3[1].trim();
          inGroupSubsection = false;
          continue;
        }
        if (/^#### /.test(raw)) {
          inGroupSubsection = true;
          continue;
        }
        if (!/^- \[ \] /.test(raw))
          continue;
        if (raw.includes("[id::"))
          continue;
        if (raw.includes("_No tasks found._"))
          continue;
        if (inGroupSubsection) {
          console.warn(`habitica-fullsync VaultHandler.getCreatableLinesFromFile: skipping creatable line under "#### Group Tasks" (group-task creation unsupported): ${raw}`);
          continue;
        }
        const noteSegs = [];
        const checklistTexts = [];
        for (let j = i + 1; j < lines.length; j++) {
          const noteMatch = lines[j].match(/^\s{2,}> (.*)$/);
          const checkMatch = lines[j].match(/^\s{2,}- \[[ xX]\] (.*)$/);
          if (noteMatch) {
            const seg = noteMatch[1].trim();
            if (seg && !/^\[!/.test(seg))
              noteSegs.push(seg);
            continue;
          }
          if (checkMatch) {
            const t = checkMatch[1].trim();
            if (t)
              checklistTexts.push(t);
            continue;
          }
          break;
        }
        results.push({ line: raw, section, notes: noteSegs.join("\n"), checklistTexts });
      }
      return results;
    } catch (_) {
      return [];
    }
  }
  /**
   * Replaces the first exact occurrence of `oldLine` with `newLine` in a file addressed by path.
   *
   * Used for crash-safe write-back of a newly assigned `[id:: ...]` immediately after task
   * creation, so a partial failure later in the sync cannot cause the same line to be created
   * twice on the next run. Uses the path-based adapter (the file is a generated artifact that
   * may not be a tracked `TFile` at this point).
   *
   * @param filePath Vault-relative path to the file.
   * @param oldLine  The exact current line text to replace.
   * @param newLine  The replacement line text.
   */
  async updateLineInFile(filePath, oldLine, newLine) {
    try {
      const content = await this.app.vault.adapter.read(filePath);
      if (!content.includes(oldLine)) {
        console.warn(`habitica-fullsync VaultHandler.updateLineInFile: could not locate line in "${filePath}".`);
        return;
      }
      await this.app.vault.adapter.write(filePath, content.replace(oldLine, newLine));
    } catch (err) {
      console.error(`habitica-fullsync VaultHandler.updateLineInFile: failed to update "${filePath}":`, err);
    }
  }
  /**
   * Ensures a folder exists in the vault, creating it if necessary.
   * Does nothing if `folderPath` is an empty string.
   * @param folderPath Vault-relative path (e.g. `'Habitica/Tasks'`).
   */
  async ensureFolder(folderPath) {
    if (!folderPath)
      return;
    const folderExists = await this.app.vault.adapter.exists(folderPath);
    if (!folderExists) {
      await this.app.vault.createFolder(folderPath);
    }
  }
  /**
   * Writes a string to a vault file, creating or overwriting it.
   * Uses `vault.adapter.write` to allow writing to paths that may or may not already exist.
   * @param filePath Vault-relative path (e.g. `'Habitica/habitica-fullsync.md'`).
   * @param content  The complete string content to write.
   */
  async writeFile(filePath, content) {
    await this.app.vault.adapter.write(filePath, content);
  }
};

// src/helpers.ts
var RESERVED_TYPE_TAGS = /* @__PURE__ */ new Set(["daily", "habit", "reward"]);
function isMobilePlatform() {
  const win = window;
  return !!(win == null ? void 0 : win.isMobile) || !!(win == null ? void 0 : win.cordova);
}
function sanitizeTag(name) {
  const sanitized = String(name != null ? name : "").trim().replace(/\s+/g, "-").replace(/[^\p{L}\p{N}_\-/]+/gu, "").replace(/-{2,}/g, "-").replace(/^-+|-+$/g, "");
  return sanitized.length > 0 ? sanitized : "unknown";
}
function buildTagReverseIndex(tagLookup) {
  const index = {};
  for (const [id, name] of Object.entries(tagLookup)) {
    index[normalizeTagKey(name)] = id;
  }
  return index;
}
function normalizeTagKey(name) {
  return String(name != null ? name : "").trim().toLowerCase().replace(/[\s_-]+/g, " ");
}
function buildDataviewBlock(type, source) {
  const quoted = `"${source}"`;
  const base = [
    "FROM " + quoted,
    "FLATTEN file.lists AS item"
  ];
  let table;
  let where;
  let sort = "";
  switch (type) {
    case "todo":
      table = 'TABLE WITHOUT ID item.text AS "To-Do", item.priority AS "Priority", item.due AS "Due", item.completion AS "Done"';
      where = 'WHERE item.id AND !contains(item.tags, "#daily") AND !contains(item.tags, "#habit") AND !contains(item.tags, "#reward")';
      sort = "SORT item.due ASC";
      break;
    case "daily":
      table = 'TABLE WITHOUT ID item.text AS "Daily", item.priority AS "Priority", item.due AS "Next Due"';
      where = 'WHERE item.id AND contains(item.tags, "#daily")';
      sort = "SORT item.due ASC";
      break;
    case "habit":
      table = 'TABLE WITHOUT ID item.text AS "Habit", item.priority AS "Priority"';
      where = 'WHERE item.id AND contains(item.tags, "#habit")';
      break;
    case "reward":
      table = 'TABLE WITHOUT ID item.text AS "Reward", item.priority AS "Priority"';
      where = 'WHERE item.id AND contains(item.tags, "#reward")';
      break;
  }
  const lines = ["```dataview", table, ...base, where];
  if (sort)
    lines.push(sort);
  lines.push("```");
  return lines.join("\n");
}
function filterActive(list, type, scoredIds) {
  return list.filter((task) => task.type === type && !task.completed && !scoredIds.has(task.id));
}
function toLocaleDateStringSafe(dateInput) {
  if (!dateInput)
    return null;
  const d = new Date(dateInput);
  return isNaN(d.getTime()) ? null : d.toLocaleDateString("en-CA");
}
function formatTasks(taskList, tagLookup, TODAY) {
  if (!taskList.length)
    return ["_No tasks found._"];
  return taskList.map((task) => formatTaskLine(task, tagLookup, TODAY));
}
function formatTaskLine(task, tagLookup, TODAY) {
  var _a;
  const status = task.completed ? "x" : " ";
  const cleanText = task.text.replace(/^#{1,6}\s+/, "").trim();
  const tagBodies = (Array.isArray(task.tags) ? task.tags : []).map((id) => sanitizeTag(tagLookup[id] || "unknown"));
  const tags = [...new Set(tagBodies)].map((body) => `#${body}`);
  if (task.type === "daily")
    tags.push("#daily");
  if (task.type === "habit")
    tags.push("#habit");
  if (task.type === "reward")
    tags.push("#reward");
  const priorityMap = { "2": "high", "1.5": "medium", "1": "low", "0.1": "lowest" };
  const priority = priorityMap[String(task.priority)] || "Unknown";
  let line = `- [${status}] ${cleanText} ${tags.join(" ")} [id:: ${task.id}] [priority:: ${priority}]`;
  const dueDateStr = toLocaleDateStringSafe(task.date);
  if (task.type === "todo" && dueDateStr) {
    line += ` [due:: ${dueDateStr}]`;
  }
  if (task.type === "daily") {
    const dueDate = getNextDailyDueDate(task);
    if (dueDate)
      line += ` [due:: ${dueDate}]`;
  }
  if (task.completed && task.type !== "habit") {
    line += ` [completion:: ${TODAY}]`;
  }
  const blocks = [line];
  const notesRaw = task.notes != null ? String(task.notes) : "";
  if (notesRaw.trim()) {
    const segments = notesRaw.split(/[\r\n]+/).map((s) => s.replace(/^#{1,6}\s+/, "").trim()).filter((s) => s.length > 0);
    if (segments.length > 0) {
      blocks.push("  > [!note]");
      for (const seg of segments)
        blocks.push(`  > ${seg}`);
    }
  }
  const checklist = Array.isArray(task.checklist) ? task.checklist : [];
  for (const item of checklist) {
    const itemText = String((_a = item.text) != null ? _a : "").replace(/^#{1,6}\s+/, "").trim();
    if (!itemText)
      continue;
    blocks.push(`  - [${item.completed ? "x" : " "}] ${itemText}`);
  }
  return blocks.join("\n");
}
function getNextDailyDueDate(task) {
  try {
    const start = new Date(task.startDate);
    if (isNaN(start.getTime()))
      return null;
    const today = new Date();
    const freq = task.frequency;
    const everyX = task.everyX || 1;
    const baseDate = start > today ? new Date(start) : new Date(today);
    if (freq === "daily") {
      const startMs = Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), start.getUTCDate());
      const todayMs = Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate());
      if (todayMs < startMs) {
        return start.toLocaleDateString("en-CA");
      }
      const dayMs = 24 * 60 * 60 * 1e3;
      const daysSinceStart = Math.round((todayMs - startMs) / dayMs);
      const remainder = daysSinceStart % everyX;
      const daysUntilNext = remainder === 0 ? 0 : everyX - remainder;
      const nextMs = todayMs + daysUntilNext * dayMs;
      const next = new Date(nextMs);
      return next.toLocaleDateString("en-CA");
    }
    if (freq === "weekly" && task.repeat) {
      const repeatDays = task.repeat;
      const weekdayKeys = ["su", "m", "t", "w", "th", "f", "s"];
      for (let i = 0; i < 30; i++) {
        const check = new Date(baseDate);
        check.setDate(baseDate.getDate() + i);
        const key = weekdayKeys[check.getDay()];
        if (repeatDays[key] && check >= start) {
          return check.toLocaleDateString("en-CA");
        }
      }
    }
    return null;
  } catch (err) {
    console.error("habitica-fullsync helpers.getNextDailyDueDate: error calculating daily due date:", err);
    return null;
  }
}
function sectionToType(section) {
  switch (section.trim().toLowerCase()) {
    case "dailies":
      return "daily";
    case "habits":
      return "habit";
    case "rewards":
      return "reward";
    case "to-dos":
    case "todos":
    case "to dos":
      return "todo";
    default:
      return "todo";
  }
}
function isValidDateString(s) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(s))
    return false;
  const d = new Date(`${s}T00:00:00Z`);
  return !isNaN(d.getTime()) && d.toISOString().slice(0, 10) === s;
}
function parseTaskLine(line, section, reverseIndex, notes, checklistTexts) {
  const type = sectionToType(section);
  let rest = line.replace(/^- \[ \]\s*/, "");
  let priority;
  const priorityMatch = rest.match(/\[priority:: (high|medium|low|lowest)\]/i);
  if (priorityMatch) {
    const map = { high: 2, medium: 1.5, low: 1, lowest: 0.1 };
    priority = map[priorityMatch[1].toLowerCase()];
  }
  let date;
  let startDate;
  let frequency;
  const dueMatch = rest.match(/\[due:: (\d{4}-\d{2}-\d{2})\]/);
  if (dueMatch && isValidDateString(dueMatch[1])) {
    if (type === "todo")
      date = dueMatch[1];
    else if (type === "daily") {
      startDate = dueMatch[1];
      frequency = "daily";
    }
  } else if (type === "daily") {
    frequency = "daily";
  }
  const tagIds = [];
  const newTagNames = [];
  const seenTagKeys = /* @__PURE__ */ new Set();
  const tagMatches = rest.match(/#[\p{L}\p{N}_\-/]+/gu) || [];
  for (const tag of tagMatches) {
    const body = tag.slice(1);
    const key = normalizeTagKey(body);
    if (RESERVED_TYPE_TAGS.has(key))
      continue;
    if (seenTagKeys.has(key))
      continue;
    seenTagKeys.add(key);
    const existingId = reverseIndex[key];
    if (existingId)
      tagIds.push(existingId);
    else
      newTagNames.push(body.replace(/-/g, " "));
  }
  const text = rest.replace(/\[[a-zA-Z]+:: [^\]]*\]/g, "").replace(/#[\p{L}\p{N}_\-/]+/gu, "").replace(/%%scored%%/g, "").replace(/\s{2,}/g, " ").trim();
  return {
    text,
    type,
    priority,
    date,
    startDate,
    frequency,
    tagIds,
    newTagNames,
    notes: notes.trim() ? notes.trim() : void 0,
    checklistTexts
  };
}

// src/sync-manager.ts
var SyncManager = class {
  /**
   * @param apiClient    Configured Habitica API client.
   * @param vaultHandler Vault read/write helper.
   * @param settings     Current plugin settings (read each sync run, reflects live UI changes).
   * @param noticeFn     Callback that displays a user-facing notice (e.g. `msg => new Notice(msg)`).
   */
  constructor(apiClient, vaultHandler, settings, noticeFn) {
    this.apiClient = apiClient;
    this.vaultHandler = vaultHandler;
    this.settings = settings;
    this.noticeFn = noticeFn;
    this._syncInFlight = false;
  }
  /**
   * Runs a full Habitica ↔ Obsidian sync.
   *
   * **Concurrency:** Returns immediately if `_syncInFlight` is already `true`. The flag is
   * reset in `finally` so a thrown error never permanently locks out future syncs.
   *
   * **Sync steps (in order):**
   * 1. Fetch user tasks, tags, and (if configured) group tasks from Habitica.
   * 2. Pre-pass: scan the sync output file for `todo`/`daily` tasks the user checked off
   *    directly in Obsidian. Score those in Habitica and add to `scoredIds`.
   *    (Habits and rewards are skipped here — habits don't become `completed: true` after
   *    scoring, so they would re-score on every sync until the file is regenerated.)
   * 3. General vault scan: find tasks completed in the last 4 days that have a
   *    `[completion:: YYYY-MM-DD]` field and no `%%scored%%` marker. Score them, write
   *    `%%scored%%` back to the vault line. IDs already in `scoredIds` are skipped.
   * 4. For completed tasks without an ID (and `disableCreating === false`): create a new
   *    Habitica to-do, score it, and write the assigned ID back to the vault line.
   * 5. Build a Markdown output document grouped by task type and source.
   * 6. Write the document to `outputFolder/habitica-fullsync.md`.
   * 7. Show a success or failure notice.
   */
  async sync() {
    var _a, _b;
    if (this._syncInFlight) {
      console.warn("habitica-fullsync SyncManager.sync: sync already in progress, skipping.");
      return;
    }
    this._syncInFlight = true;
    const { groupId, outputFolder, disableScoring, disableCreating } = this.settings;
    const TODAY = new Date().toLocaleDateString("en-CA");
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - 4);
    const filePath = outputFolder ? `${outputFolder}/habitica-fullsync.md` : "habitica-fullsync.md";
    try {
      const rawTasks = await this.apiClient.fetchUserTasks();
      const tasks = Array.isArray(rawTasks) ? rawTasks : [];
      const tags = await this.apiClient.fetchTags();
      const rawTags = Array.isArray(tags) ? tags : [];
      const tagLookup = Object.fromEntries(rawTags.map((tag) => [tag.id, tag.name]));
      let groupTasks = [];
      if (groupId) {
        try {
          const rawGroupTasks = await this.apiClient.fetchGroupTasks(groupId);
          groupTasks = Array.isArray(rawGroupTasks) ? rawGroupTasks : [];
        } catch (err) {
          console.error("habitica-fullsync SyncManager.sync: failed to fetch group tasks:", err);
        }
      }
      const allTasks = [...tasks, ...groupTasks];
      const scoredIds = /* @__PURE__ */ new Set();
      if (!disableScoring) {
        const syncFileChecked = await this.vaultHandler.getCheckedTasksFromFile(filePath);
        for (const { id } of syncFileChecked) {
          const habiticaTask = allTasks.find((t) => t.id === id);
          if (!habiticaTask || habiticaTask.completed)
            continue;
          if (habiticaTask.type !== "todo" && habiticaTask.type !== "daily")
            continue;
          try {
            await this.apiClient.scoreTask(id, "up");
            scoredIds.add(id);
          } catch (err) {
            console.error(`habitica-fullsync SyncManager.sync: failed to score sync-file task ${id}:`, err);
          }
        }
        const completedTasks = await this.vaultHandler.getRecentCompletedTasks(cutoffDate);
        for (const task of completedTasks) {
          const match = task.line.match(/\[id:: ([^\]]+)\]/);
          if (match) {
            const id = match[1];
            if (scoredIds.has(id))
              continue;
            const habiticaTask = allTasks.find((t) => t.id === id);
            if (!habiticaTask || habiticaTask.completed)
              continue;
            let direction = "up";
            if (habiticaTask.type === "habit") {
              direction = habiticaTask.up ? "up" : habiticaTask.down ? "down" : "up";
            }
            try {
              await this.apiClient.scoreTask(id, direction);
              scoredIds.add(id);
              await this.vaultHandler.updateLine(task.file, task.line + " %%scored%%");
            } catch (err) {
              console.error(`habitica-fullsync SyncManager.sync: failed to score vault task ${id}:`, err);
            }
          } else if (!disableCreating) {
            const text = task.line.replace(/^- \[x\]\s*/, "").split(" [")[0];
            try {
              const newTask = await this.apiClient.createTask({ text, type: "todo" });
              await this.apiClient.scoreTask(newTask.id, "up");
              scoredIds.add(newTask.id);
              const newLine = task.line + ` [id:: ${newTask.id}] %%scored%%`;
              await this.vaultHandler.updateLine(task.file, newLine);
            } catch (err) {
              console.error("habitica-fullsync SyncManager.sync: failed to create and score new task:", err);
            }
          }
        }
      }
      let createdCount = 0;
      let createFailures = 0;
      if (!disableCreating) {
        const reverseIndex = buildTagReverseIndex(tagLookup);
        const creatable = await this.vaultHandler.getCreatableLinesFromFile(filePath);
        for (const item of creatable) {
          try {
            const input = parseTaskLine(item.line, item.section, reverseIndex, item.notes, item.checklistTexts);
            if (!input.text) {
              console.warn(`habitica-fullsync SyncManager.sync: skipping creatable line with empty title: ${item.line}`);
              continue;
            }
            for (const name of input.newTagNames) {
              try {
                const tag = await this.apiClient.createTag(name);
                tagLookup[tag.id] = tag.name;
                reverseIndex[normalizeTagKey(tag.name)] = tag.id;
                input.tagIds.push(tag.id);
              } catch (err) {
                console.error(`habitica-fullsync SyncManager.sync: failed to create tag "${name}":`, err);
              }
            }
            const created = await this.apiClient.createTask({
              text: input.text,
              type: input.type,
              priority: input.priority,
              date: input.date,
              startDate: input.startDate,
              frequency: input.frequency,
              tags: input.tagIds,
              notes: input.notes
            });
            let checklist = Array.isArray(created.checklist) ? created.checklist : [];
            for (const ctext of input.checklistTexts) {
              try {
                const updated = await this.apiClient.addChecklistItem(created.id, ctext);
                if (Array.isArray(updated.checklist))
                  checklist = updated.checklist;
              } catch (err) {
                console.error(`habitica-fullsync SyncManager.sync: failed to add checklist item to ${created.id}:`, err);
              }
            }
            const merged = {
              ...created,
              tags: Array.isArray(created.tags) ? created.tags : input.tagIds,
              notes: (_b = (_a = created.notes) != null ? _a : input.notes) != null ? _b : null,
              checklist
            };
            tasks.push(merged);
            await this.vaultHandler.updateLineInFile(filePath, item.line, `${item.line} [id:: ${created.id}]`);
            createdCount++;
          } catch (err) {
            createFailures++;
            console.error(`habitica-fullsync SyncManager.sync: failed to create task from line "${item.line}":`, err);
          }
        }
      }
      const dailiesPersonal = filterActive(tasks, "daily", scoredIds);
      const todosPersonal = filterActive(tasks, "todo", scoredIds);
      const rewardsPersonal = filterActive(tasks, "reward", scoredIds);
      const habitsPersonal = filterActive(tasks, "habit", scoredIds);
      const dailiesGroup = filterActive(groupTasks, "daily", scoredIds);
      const todosGroup = filterActive(groupTasks, "todo", scoredIds);
      const rewardsGroup = filterActive(groupTasks, "reward", scoredIds);
      const habitsGroup = filterActive(groupTasks, "habit", scoredIds);
      const totalRendered = dailiesPersonal.length + dailiesGroup.length + todosPersonal.length + todosGroup.length + rewardsPersonal.length + rewardsGroup.length + habitsPersonal.length + habitsGroup.length;
      const breakdown = [
        `${dailiesPersonal.length + dailiesGroup.length} dailies`,
        `${todosPersonal.length + todosGroup.length} to-dos`,
        `${rewardsPersonal.length + rewardsGroup.length} rewards`,
        `${habitsPersonal.length + habitsGroup.length} habits`
      ].join(" \xB7 ");
      const output = [
        `## Habitica Sync \u2014 ${TODAY}`,
        `*${totalRendered} active tasks: ${breakdown}*`,
        ``
      ];
      const dataviewSource = outputFolder ? `${outputFolder}/habitica-fullsync` : "habitica-fullsync";
      const writeSection = (title, type, personal, group) => {
        output.push(`### ${title}`);
        output.push(...formatTasks(personal, tagLookup, TODAY));
        if (groupId) {
          output.push("");
          output.push("#### Group Tasks");
          output.push(...formatTasks(group, tagLookup, TODAY));
        }
        output.push("");
        output.push(buildDataviewBlock(type, dataviewSource));
        output.push("");
      };
      writeSection("Dailies", "daily", dailiesPersonal, dailiesGroup);
      writeSection("To-Dos", "todo", todosPersonal, todosGroup);
      writeSection("Rewards", "reward", rewardsPersonal, rewardsGroup);
      writeSection("Habits", "habit", habitsPersonal, habitsGroup);
      await this.vaultHandler.ensureFolder(outputFolder);
      await this.vaultHandler.writeFile(filePath, output.join("\n"));
      let createSummary = "";
      if (createdCount > 0)
        createSummary += ` \u2014 created ${createdCount} task${createdCount === 1 ? "" : "s"}`;
      if (createFailures > 0)
        createSummary += `, ${createFailures} failed (see console)`;
      this.noticeFn(`\u2705 Habitica sync complete: ${filePath}${createSummary}`);
    } catch (err) {
      console.error("habitica-fullsync SyncManager.sync:", err);
      this.noticeFn("\u274C Habitica sync failed. Check console for details.");
    } finally {
      this._syncInFlight = false;
    }
  }
};

// src/main.ts
var HabiticaSyncFullPlugin = class extends import_obsidian.Plugin {
  /**
   * Lifecycle hook called when Obsidian loads the plugin.
   *
   * Performs in order:
   * 1. Loads persisted settings.
   * 2. Instantiates `HabiticaApiClient`, `VaultHandler`, and `SyncManager`.
   * 3. Registers the `sync-habitica` command in the command palette.
   * 4. Adds the settings tab.
   * 5. If `autoSync` is enabled and the current platform matches `autoSyncPlatform`,
   *    runs an immediate sync and starts the repeat interval.
   */
  async onload() {
    await this.loadSettings();
    this.apiClient = new HabiticaApiClient(this.settings.apiUser, this.settings.apiToken);
    this.vaultHandler = new VaultHandler(this.app);
    this.syncManager = new SyncManager(
      this.apiClient,
      this.vaultHandler,
      this.settings,
      (msg) => new import_obsidian.Notice(msg)
    );
    this.addCommand({
      id: "sync-habitica",
      name: "Sync Habitica Tasks",
      callback: () => this.syncHabitica()
    });
    this.addSettingTab(new HabiticaSyncSettingTab(this.app, this));
    const platformSetting = this.settings.autoSyncPlatform || "both";
    const isMobile = isMobilePlatform();
    let shouldAutoSync = false;
    if (platformSetting === "both")
      shouldAutoSync = true;
    else if (platformSetting === "desktop" && !isMobile)
      shouldAutoSync = true;
    else if (platformSetting === "mobile" && isMobile)
      shouldAutoSync = true;
    if (this.settings.autoSync && shouldAutoSync) {
      this.syncHabitica();
      const intervalMs = this.settings.syncInterval * 60 * 1e3;
      this.autoSyncInterval = window.setInterval(() => this.syncHabitica(), intervalMs);
    }
  }
  /**
   * Lifecycle hook called when the plugin is disabled or Obsidian shuts down.
   * Clears the auto-sync interval to prevent memory leaks and stale callbacks.
   */
  onunload() {
    if (this.autoSyncInterval) {
      clearInterval(this.autoSyncInterval);
    }
  }
  /**
   * Loads plugin settings from Obsidian's data store, merging with defaults.
   *
   * Uses `Object.assign` so stored values override defaults while unknown stored keys
   * (e.g. a removed `machineId` from a previous version's `data.json`) are silently ignored.
   */
  async loadSettings() {
    this.settings = Object.assign({
      apiUser: "",
      apiToken: "",
      groupId: "",
      outputFolder: "",
      autoSync: false,
      autoSyncPlatform: "both",
      syncInterval: 30,
      disableScoring: false,
      disableCreating: false
    }, await this.loadData());
  }
  /**
   * Persists the current settings to Obsidian's data store and rebuilds the API client
   * so credential changes (API User / API Token) take effect immediately without
   * requiring a plugin reload.
   * Called after every settings change in {@link HabiticaSyncSettingTab}.
   */
  async saveSettings() {
    await this.saveData(this.settings);
    this.apiClient = new HabiticaApiClient(this.settings.apiUser, this.settings.apiToken);
    this.syncManager = new SyncManager(
      this.apiClient,
      this.vaultHandler,
      this.settings,
      (msg) => new import_obsidian.Notice(msg)
    );
  }
  /**
   * Triggers a full Habitica ↔ Obsidian sync.
   * Delegates to `SyncManager.sync()`, which handles concurrency guarding and error reporting.
   */
  async syncHabitica() {
    await this.syncManager.sync();
  }
};
var HabiticaSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  /**
   * @param app    The Obsidian application instance.
   * @param plugin The parent plugin instance, providing access to settings and save methods.
   */
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /**
   * Renders all settings controls into the settings container.
   * Settings (in order): API User, API Token (password-masked), Group ID, Output Folder,
   * Automatic Sync toggle, Auto Sync Platform dropdown, Sync Interval, Disable Scoring,
   * Disable Creating New Tasks.
   */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("API User").setDesc("Your Habitica API User ID").addText((text) => text.setPlaceholder("Enter API User").setValue(this.plugin.settings.apiUser).onChange(async (value) => {
      this.plugin.settings.apiUser = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("API Token").setDesc("Your Habitica API Token (kept in Obsidian local storage; do not share your vault)").addText((text) => {
      text.setPlaceholder("Enter API Token").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
      return text;
    });
    new import_obsidian.Setting(containerEl).setName("Group ID").setDesc("Your Habitica Group ID for shared tasks").addText((text) => text.setPlaceholder("Enter Group ID").setValue(this.plugin.settings.groupId).onChange(async (value) => {
      this.plugin.settings.groupId = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Output folder").setDesc("Folder where habitica-fullsync.md will be saved (leave blank for vault root)").addText((text) => text.setPlaceholder("e.g., Habitica").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
      this.plugin.settings.outputFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Automatic sync").setDesc("Enable automatic sync on load and every X minutes").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
      this.plugin.settings.autoSync = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto sync platform").setDesc("Choose which devices should run auto sync").addDropdown((dropdown) => {
      dropdown.addOption("both", "Both Desktop and Mobile").addOption("desktop", "Desktop Only").addOption("mobile", "Mobile Only").setValue(this.plugin.settings.autoSyncPlatform || "both").onChange(async (value) => {
        this.plugin.settings.autoSyncPlatform = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Sync interval (minutes)").setDesc("How often to run auto-sync when enabled").addText((text) => text.setPlaceholder("e.g., 30").setValue(String(this.plugin.settings.syncInterval)).onChange(async (value) => {
      const num = parseInt(value, 10);
      if (!isNaN(num) && num > 0) {
        this.plugin.settings.syncInterval = num;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Disable scoring").setDesc("Enable this to prevent scoring tasks in Habitica (read-only sync)").addToggle((toggle) => toggle.setValue(this.plugin.settings.disableScoring).onChange(async (value) => {
      this.plugin.settings.disableScoring = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Disable creating new tasks").setDesc("Enable this to prevent creating new tasks in Habitica from non-habitica tasks completed in Obsidian").addToggle((toggle) => toggle.setValue(this.plugin.settings.disableCreating).onChange(async (value) => {
      this.plugin.settings.disableCreating = value;
      await this.plugin.saveSettings();
    }));
  }
};
var main_default = HabiticaSyncFullPlugin;
