/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HabiticaSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var HabiticaSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    return [];
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("API user").setDesc("Your Habitica API user ID").addText((text) => text.setPlaceholder("Enter API user").setValue(this.plugin.pluginSettings.userId).onChange(async (value) => {
      this.plugin.pluginSettings.userId = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("API token").setDesc("Your Habitica API token, stored securely via Obsidian SecretStorage").addComponent((el) => new import_obsidian.SecretComponent(this.app, el).setValue(this.plugin.pluginSettings.apiTokenSecretName).onChange(async (value) => {
      this.plugin.pluginSettings.apiTokenSecretName = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Group ID").setDesc("Your Habitica group ID for shared tasks").addText((text) => {
      var _a;
      return text.setPlaceholder("Enter group ID").setValue((_a = this.plugin.pluginSettings.groupId) != null ? _a : "").onChange(async (value) => {
        this.plugin.pluginSettings.groupId = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Output file path").setDesc("Path where Habitica tasks will be synced").addText((text) => text.setPlaceholder("Habitica/Sync.md").setValue(this.plugin.pluginSettings.syncFilePath).onChange(async (value) => {
      this.plugin.pluginSettings.syncFilePath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Automatic sync").setDesc("Enable automatic sync on load and every x minutes").addToggle((toggle) => toggle.setValue(Boolean(this.plugin.pluginSettings.autoSync)).onChange(async (value) => {
      this.plugin.pluginSettings.autoSync = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto sync platform").setDesc("Choose which devices should run auto sync").addDropdown((dropdown) => {
      var _a;
      return dropdown.addOption("both", "Both desktop and mobile").addOption("desktop", "Desktop only").addOption("mobile", "Mobile only").setValue((_a = this.plugin.pluginSettings.autoSyncPlatform) != null ? _a : "both").onChange(async (value) => {
        this.plugin.pluginSettings.autoSyncPlatform = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Sync interval (minutes)").setDesc("How often to run auto-sync when enabled").addText((text) => {
      var _a;
      return text.setPlaceholder("E.g., 30").setValue(String((_a = this.plugin.pluginSettings.syncInterval) != null ? _a : 30)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.pluginSettings.syncInterval = num;
          await this.plugin.saveSettings();
        } else {
          new import_obsidian.Notice("Sync interval must be a positive number");
        }
      });
    });
    new import_obsidian.Setting(containerEl).setName("Disable scoring").setDesc("Enable this to prevent scoring tasks in Habitica (read-only sync)").addToggle((toggle) => toggle.setValue(Boolean(this.plugin.pluginSettings.disableScoring)).onChange(async (value) => {
      this.plugin.pluginSettings.disableScoring = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Disable creating new tasks").setDesc("Enable this to prevent creating new tasks in Habitica from non-Habitica tasks completed in Obsidian").addToggle((toggle) => toggle.setValue(Boolean(this.plugin.pluginSettings.disableCreating)).onChange(async (value) => {
      this.plugin.pluginSettings.disableCreating = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Scan vault for completed tasks").setDesc("Scan all markdown files in your vault for checked-off tasks with a [completion::] field and score them in Habitica. When off, only the sync file (Habitica-fullsync.md) is checked.").addToggle((toggle) => toggle.setValue(Boolean(this.plugin.pluginSettings.enableVaultScan)).onChange(async (value) => {
      this.plugin.pluginSettings.enableVaultScan = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Completion lookback (days)").setDesc("How many days back to look for recently completed tasks in your vault. Defaults to 4 \u2014 covers a typical weekend gap.").addText((text) => {
      var _a;
      return text.setPlaceholder("4").setValue(String((_a = this.plugin.pluginSettings.completionLookbackDays) != null ? _a : 4)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.pluginSettings.completionLookbackDays = num;
          await this.plugin.saveSettings();
        } else {
          new import_obsidian.Notice("Lookback must be a positive number");
        }
      });
    });
  }
};

// src/types/habitica.ts
var DEFAULT_SETTINGS = {
  userId: "",
  apiTokenSecretName: "",
  syncFilePath: "Habitica/Sync.md",
  groupId: "",
  autoSync: false,
  autoSyncPlatform: "both",
  syncInterval: 30,
  disableScoring: false,
  disableCreating: false,
  enableVaultScan: false,
  completionLookbackDays: 4
};

// src/api/client.ts
var import_obsidian2 = require("obsidian");
var HabiticaApiClient = class {
  // Required by Habitica API guidelines
  /**
   * Initializes a new instance of the API client.
   * @param credentials The user ID and API token.
   */
  constructor(credentials) {
    __publicField(this, "credentials", credentials);
    __publicField(this, "baseUrl", "https://habitica.com/api/v3");
    __publicField(this, "clientId", "bfb65555-5517-47b6-acb5-31215b3c3c13-obsidian-habitica-fullsync");
  }
  /**
   * Generates the required authentication and client headers.
   * @returns A record of HTTP headers.
   */
  getHeaders() {
    return {
      "x-client": this.clientId,
      "x-api-user": this.credentials.userId,
      "x-api-key": this.credentials.apiToken,
      "Content-Type": "application/json"
    };
  }
  /**
   * Internal method to dispatch requests using Obsidian's requestUrl.
   * @param method The HTTP method.
   * @param endpoint The API endpoint (relative to v3).
   * @param body Optional JSON body.
   * @returns The raw HabiticaResponse.
   */
  async request(method, endpoint, body) {
    const url = `${this.baseUrl}${endpoint}`;
    const params = {
      url,
      method,
      headers: this.getHeaders()
    };
    if (body) {
      params.body = JSON.stringify(body);
    }
    try {
      const response = await (0, import_obsidian2.requestUrl)(params);
      if (response.status >= 400) {
        console.error(`[Habitica API Error] ${method} ${url}`, response.json);
        throw new Error(`Habitica API returned status ${response.status}`);
      }
      return response.json;
    } catch (error) {
      console.error(`[Habitica API Exception]`, error);
      throw error;
    }
  }
  // --- Task Endpoints ---
  /**
   * Fetches all tasks for the authenticated user.
   * @returns An array of HabiticaTask objects.
   */
  async fetchAllTasks() {
    const response = await this.request("GET", "/tasks/user");
    return response.data;
  }
  /**
   * Creates a new task in Habitica.
   * @param taskData Partial task payload.
   * @returns The created HabiticaTask.
   */
  async createTask(taskData) {
    const response = await this.request("POST", "/tasks/user", taskData);
    return response.data;
  }
  /**
   * Updates an existing task in Habitica.
   * @param taskId The UUID of the task.
   * @param updates The fields to update.
   * @returns The updated HabiticaTask.
   */
  async updateTask(taskId, updates) {
    const response = await this.request("PUT", `/tasks/${taskId}`, updates);
    return response.data;
  }
  /**
   * Deletes a task from Habitica.
   * @param taskId The UUID of the task.
   */
  async deleteTask(taskId) {
    await this.request("DELETE", `/tasks/${taskId}`);
  }
  /**
   * Scores a task (e.g. checking off a daily, or pressing + on a habit).
   * @param taskId The UUID of the task.
   * @param direction 'up' or 'down'.
   * @returns The updated task state or rewards.
   */
  async scoreTask(taskId, direction) {
    const response = await this.request("POST", `/tasks/${taskId}/score/${direction}`);
    return response.data;
  }
  // --- Checklist Endpoints ---
  /**
   * Adds a checklist item to an existing task.
   * @param taskId The UUID of the task.
   * @param text The text for the new checklist item.
   * @returns The created checklist item data.
   */
  async addChecklistItem(taskId, text) {
    const response = await this.request("POST", `/tasks/${taskId}/checklist`, { text });
    return response.data;
  }
  /**
   * Updates the text of an existing checklist item.
   * @param taskId The UUID of the parent task.
   * @param itemId The UUID of the checklist item.
   * @param text The new text.
   * @returns The updated checklist item data.
   */
  async updateChecklistItem(taskId, itemId, text) {
    const response = await this.request("PUT", `/tasks/${taskId}/checklist/${itemId}`, { text });
    return response.data;
  }
  /**
   * Scores (toggles) a checklist item.
   * @param taskId The UUID of the parent task.
   * @param itemId The UUID of the checklist item.
   * @returns The updated state of the checklist item.
   */
  async scoreChecklistItem(taskId, itemId) {
    const response = await this.request("POST", `/tasks/${taskId}/checklist/${itemId}/score`);
    return response.data;
  }
  /**
   * Deletes a checklist item.
   * @param taskId The UUID of the parent task.
   * @param itemId The UUID of the checklist item.
   */
  async deleteChecklistItem(taskId, itemId) {
    await this.request("DELETE", `/tasks/${taskId}/checklist/${itemId}`);
  }
};

// src/store/json-store.ts
var JsonStore = class {
  constructor(adapter, pluginDir) {
    __publicField(this, "adapter");
    __publicField(this, "pluginDir");
    this.adapter = adapter;
    this.pluginDir = pluginDir;
  }
  getFilePath(type) {
    return `${this.pluginDir}/states/state_${type}s.json`;
  }
  /**
   * Loads the JSON state for a specific task type.
   */
  async loadState(type) {
    const filePath = this.getFilePath(type);
    const exists = await this.adapter.exists(filePath);
    if (!exists) {
      return [];
    }
    try {
      const content = await this.adapter.read(filePath);
      return JSON.parse(content);
    } catch (error) {
      console.error(`[Habitica Fullsync] Failed to load ${type} state:`, error);
      return [];
    }
  }
  /**
   * Saves the JSON state for a specific task type.
   */
  async saveState(type, tasks) {
    const filePath = this.getFilePath(type);
    const folderPath = `${this.pluginDir}/states`;
    try {
      const folderExists = await this.adapter.exists(folderPath);
      if (!folderExists) {
        await this.adapter.mkdir(folderPath);
      }
      const content = JSON.stringify(tasks, null, 2);
      await this.adapter.write(filePath, content);
    } catch (error) {
      console.error(`[Habitica Fullsync] Failed to save ${type} state:`, error);
    }
  }
  /**
   * Loads all states into a single record.
   */
  async loadAll() {
    const [habits, dailies, todos, rewards] = await Promise.all([
      this.loadState("habit"),
      this.loadState("daily"),
      this.loadState("todo"),
      this.loadState("reward")
    ]);
    return {
      habit: habits,
      daily: dailies,
      todo: todos,
      reward: rewards
    };
  }
  /**
   * Saves all states from a record.
   */
  async saveAll(state) {
    await Promise.all([
      this.saveState("habit", state.habit),
      this.saveState("daily", state.daily),
      this.saveState("todo", state.todo),
      this.saveState("reward", state.reward)
    ]);
  }
};

// src/api/queue.ts
var ActionQueue = class {
  constructor() {
    __publicField(this, "queue", []);
    __publicField(this, "isProcessing", false);
    // Strict delay between requests to be safe (30 requests per minute = 1 every 2000ms)
    __publicField(this, "defaultDelayMs", 2e3);
    __publicField(this, "backoffDelayMs", 6e4);
  }
  // 1 minute backoff if we hit a 429
  /**
   * Enqueues an async action.
   * @param action A function returning a Promise.
   * @returns A promise that resolves when the action completes.
   */
  enqueue(action) {
    return new Promise((resolve, reject) => {
      this.queue.push(async () => {
        try {
          const result = await action();
          resolve(result);
        } catch (error) {
          reject(error instanceof Error ? error : new Error(String(error)));
          throw error;
        }
      });
      void this.processQueue();
    });
  }
  /**
   * Processes the queued actions sequentially with a rate limit delay.
   */
  async processQueue() {
    if (this.isProcessing || this.queue.length === 0) {
      return;
    }
    this.isProcessing = true;
    while (this.queue.length > 0) {
      const action = this.queue.shift();
      if (action) {
        let hitRateLimit = false;
        try {
          await action();
        } catch (error) {
          const isRateLimit = error instanceof Error && error.message.includes("status 429") || typeof error === "object" && error !== null && error.status === 429;
          if (isRateLimit) {
            console.error("[ActionQueue] Rate limit hit (429). Backing off...");
            hitRateLimit = true;
          } else {
            console.error("[ActionQueue] Action failed:", error);
          }
        }
        if (this.queue.length > 0) {
          if (hitRateLimit) {
            await this.delay(this.backoffDelayMs);
          } else {
            await this.delay(this.defaultDelayMs);
          }
        }
      }
    }
    this.isProcessing = false;
  }
  /**
   * Helper to delay execution.
   * @param ms Milliseconds to delay.
   */
  delay(ms) {
    return new Promise((resolve) => window.setTimeout(resolve, ms));
  }
};

// src/sync/diff-engine.ts
var DiffEngine = class {
  constructor(apiClient, queue, onConflict) {
    __publicField(this, "apiClient", apiClient);
    __publicField(this, "queue", queue);
    __publicField(this, "onConflict", onConflict);
  }
  /**
   * Determines if the local markdown task is different from the JSON state task.
   * Checks updatable fields.
   */
  hasMarkdownChanged(localJson, mdTask) {
    if (localJson.text !== mdTask.text) return true;
    if (localJson.completed !== mdTask.completed) return true;
    if (localJson.notes !== mdTask.notes) return true;
    if (localJson.priority !== mdTask.priority) return true;
    if (localJson.attribute !== mdTask.attribute) return true;
    if (localJson.type === "daily") {
      if (localJson.frequency !== mdTask.frequency) return true;
    }
    if (localJson.type === "todo") {
      if (localJson.date !== mdTask.due) return true;
    }
    if (localJson.type === "habit") {
      if (localJson.up !== mdTask.up) return true;
      if (localJson.down !== mdTask.down) return true;
    }
    if (localJson.type === "reward") {
      if (localJson.value !== mdTask.value) return true;
    }
    if (localJson.checklist && mdTask.checklist) {
      if (localJson.checklist.length !== mdTask.checklist.length) return true;
      for (let i = 0; i < localJson.checklist.length; i++) {
        if (localJson.checklist[i].text !== mdTask.checklist[i].text) return true;
        if (localJson.checklist[i].completed !== mdTask.checklist[i].completed) return true;
      }
    }
    return false;
  }
  /**
   * Resolves differences between Local JSON, Remote API, and Local Markdown.
   * Returns the finalized lists of Markdown Tasks to be written back to the file,
   * and the finalized API tasks to be written back to the JSON state.
   */
  async resolve(localState, remoteState, markdownTasks) {
    const updatedRemoteState = { ...remoteState };
    const finalizedMarkdownTasks = [];
    for (const mdTask of markdownTasks) {
      const isDeleted = mdTask.rawInlineFields["delete"] === "true" || mdTask.rawInlineFields["status"] === "delete";
      if (isDeleted && mdTask.id) {
        if (remoteState[mdTask.id]) {
          await this.queue.enqueue(() => this.apiClient.deleteTask(mdTask.id));
          delete updatedRemoteState[mdTask.id];
        }
        continue;
      }
      if (!mdTask.id) {
        const created = await this.queue.enqueue(() => this.apiClient.createTask({
          text: mdTask.text,
          type: mdTask.type,
          notes: mdTask.notes,
          priority: mdTask.priority,
          attribute: mdTask.attribute,
          date: mdTask.due,
          value: mdTask.value
        }));
        updatedRemoteState[created.id] = created;
        mdTask.id = created.id;
        finalizedMarkdownTasks.push(mdTask);
        continue;
      }
      const localJson = localState[mdTask.id];
      const remoteJson = remoteState[mdTask.id];
      if (!localJson && remoteJson) {
        finalizedMarkdownTasks.push(mdTask);
        continue;
      }
      if (localJson && remoteJson) {
        const apiChanged = localJson.updatedAt !== remoteJson.updatedAt;
        const mdChanged = this.hasMarkdownChanged(localJson, mdTask);
        if (apiChanged && mdChanged) {
          const resolution = await this.onConflict(mdTask, remoteJson);
          if (resolution === "markdown") {
            await this.pushMarkdownUpdates(mdTask, remoteJson);
            finalizedMarkdownTasks.push(mdTask);
          } else if (resolution === "api") {
            finalizedMarkdownTasks.push(this.apiToMarkdown(remoteJson, mdTask));
          } else {
            finalizedMarkdownTasks.push(mdTask);
          }
        } else if (apiChanged && !mdChanged) {
          finalizedMarkdownTasks.push(this.apiToMarkdown(remoteJson, mdTask));
        } else if (!apiChanged && mdChanged) {
          await this.pushMarkdownUpdates(mdTask, remoteJson);
          finalizedMarkdownTasks.push(mdTask);
        } else {
          finalizedMarkdownTasks.push(mdTask);
        }
      } else if (localJson && !remoteJson) {
      }
    }
    const mdTaskIds = new Set(markdownTasks.map((t) => t.id).filter((id) => id !== void 0));
    for (const [id, remoteJson] of Object.entries(remoteState)) {
      if (!mdTaskIds.has(id) && updatedRemoteState[id]) {
        finalizedMarkdownTasks.push(this.apiToMarkdown(remoteJson));
      }
    }
    return { updatedRemoteState, finalizedMarkdownTasks };
  }
  async pushMarkdownUpdates(mdTask, remoteJson) {
    if (mdTask.completed !== remoteJson.completed && mdTask.type !== "reward") {
      await this.queue.enqueue(() => this.apiClient.scoreTask(mdTask.id, mdTask.completed ? "up" : "down"));
    }
    const updates = {
      text: mdTask.text,
      notes: mdTask.notes,
      priority: mdTask.priority,
      attribute: mdTask.attribute
    };
    if (mdTask.type === "daily" && mdTask.frequency) updates.frequency = mdTask.frequency;
    if (mdTask.type === "todo" && mdTask.due) updates.date = mdTask.due;
    if (mdTask.type === "reward" && mdTask.value) updates.value = mdTask.value;
    await this.queue.enqueue(() => this.apiClient.updateTask(mdTask.id, updates));
  }
  apiToMarkdown(apiTask, existingMdTask) {
    const mdTask = {
      id: apiTask.id,
      text: apiTask.text,
      completed: apiTask.completed || false,
      type: apiTask.type,
      tags: apiTask.tags || [],
      notes: apiTask.notes,
      rawInlineFields: existingMdTask ? existingMdTask.rawInlineFields : {}
    };
    if (apiTask.checklist) {
      mdTask.checklist = apiTask.checklist.map((item) => ({
        id: item.id,
        text: item.text,
        completed: item.completed
      }));
    }
    if (apiTask.priority) mdTask.priority = apiTask.priority;
    if (apiTask.attribute) mdTask.attribute = apiTask.attribute;
    if (apiTask.type === "daily" && apiTask.frequency) mdTask.frequency = apiTask.frequency;
    if (apiTask.type === "todo" && apiTask.date) mdTask.due = apiTask.date;
    if (apiTask.type === "habit") {
      if (apiTask.up !== void 0) mdTask.up = apiTask.up;
      if (apiTask.down !== void 0) mdTask.down = apiTask.down;
    }
    if (apiTask.type === "reward" && apiTask.value) mdTask.value = apiTask.value;
    return mdTask;
  }
};

// src/markdown/parser.ts
function parseMarkdown(content) {
  const state = {
    habits: [],
    dailies: [],
    todos: [],
    rewards: []
  };
  const safeContent = "\n" + content.replace(/\r\n/g, "\n");
  const blocks = safeContent.split(/\n(?=(?:-|\*) \[[ xX]\] )/);
  for (const block of blocks) {
    const trimmed = block.trim();
    if (!trimmed.startsWith("- [") && !trimmed.startsWith("* [")) continue;
    const lines = trimmed.split("\n");
    const firstLine = lines.shift();
    const bodyLines = lines.join("\n");
    const match = /^(?:-|\*) \[([ xX])\] (.*)$/.exec(firstLine);
    if (!match) continue;
    const completed = match[1].toLowerCase() === "x";
    const titleLine = match[2];
    const { text, tags, type } = parseTitleLine(titleLine);
    if (!type) continue;
    const task = parseTaskBody(text, completed, type, tags, bodyLines);
    switch (type) {
      case "habit":
        state.habits.push(task);
        break;
      case "daily":
        state.dailies.push(task);
        break;
      case "todo":
        state.todos.push(task);
        break;
      case "reward":
        state.rewards.push(task);
        break;
    }
  }
  return state;
}
function parseTitleLine(titleLine) {
  const tagsRegex = /#([\w-]+)/g;
  const tags = [];
  let type = null;
  let match;
  while ((match = tagsRegex.exec(titleLine)) !== null) {
    const tag = match[1].toLowerCase();
    tags.push(tag);
    if (["habit", "daily", "todo", "reward"].includes(tag)) {
      type = tag;
    }
  }
  const text = titleLine.replace(tagsRegex, "").trim();
  return { text, tags, type };
}
function parseTaskBody(text, completed, type, tags, bodyLines) {
  const task = {
    text,
    completed,
    type,
    tags,
    rawInlineFields: {}
  };
  const lines = bodyLines.split("\n");
  let inNote = false;
  let notes = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (trimmed.toLowerCase().startsWith("> [!note]")) {
      inNote = true;
      continue;
    }
    if (inNote) {
      if (trimmed.startsWith(">")) {
        notes.push(trimmed.substring(1).trim());
        continue;
      } else {
        inNote = false;
      }
    }
    const checklistMatch = /^(?:[+\-*]) \[([ xX])\] (.*)$/.exec(trimmed);
    if (checklistMatch) {
      if (!task.checklist) task.checklist = [];
      task.checklist.push({
        completed: checklistMatch[1].toLowerCase() === "x",
        text: checklistMatch[2].trim()
      });
      continue;
    }
    const inlineFieldRegex = /\[(\w+)::\s*([^\]]+)\]/g;
    let fieldMatch;
    while ((fieldMatch = inlineFieldRegex.exec(line)) !== null) {
      const key = fieldMatch[1];
      const value = fieldMatch[2].trim();
      task.rawInlineFields[key] = value;
      mapInlineFieldToTask(task, key, value);
    }
  }
  if (notes.length > 0) {
    task.notes = notes.join("\n");
  }
  return task;
}
function mapInlineFieldToTask(task, key, value) {
  if (key === "id") task.id = value;
  if (key === "priority") {
    const val = value.toLowerCase();
    if (val === "trivial") task.priority = 0.1;
    else if (val === "easy" || val === "low") task.priority = 1;
    else if (val === "medium") task.priority = 1.5;
    else if (val === "hard" || val === "high") task.priority = 2;
    else {
      const num = parseFloat(val);
      if (!isNaN(num)) task.priority = num;
    }
  }
  if (key === "due" || key === "date") task.due = value;
  if (key === "frequency") task.frequency = value;
  if (key === "up") task.up = value === "true";
  if (key === "down") task.down = value === "true";
  if (key === "value") task.value = parseFloat(value);
  if (key === "attribute") task.attribute = value;
}

// src/markdown/generator.ts
function generateMarkdown(state) {
  let output = "";
  output += "## Habits\n\n";
  state.habits.forEach((task) => output += generateTaskString(task) + "\n\n");
  output += "## Dailies\n\n";
  state.dailies.forEach((task) => output += generateTaskString(task) + "\n\n");
  output += "## To-Dos\n\n";
  state.todos.forEach((task) => output += generateTaskString(task) + "\n\n");
  output += "## Rewards\n\n";
  state.rewards.forEach((task) => output += generateTaskString(task) + "\n\n");
  return output.trim();
}
function generateTaskString(task) {
  const checkbox = task.completed ? "[x]" : "[ ]";
  let text = `- ${checkbox} ${task.text}`;
  const allTags = [...task.tags];
  if (!allTags.includes(task.type)) {
    allTags.push(task.type);
  }
  const tagsString = allTags.map((t) => `#${t}`).join(" ");
  if (tagsString) {
    text += ` ${tagsString}`;
  }
  let body = "";
  if (task.notes && task.notes.trim()) {
    body += `  > [!note]
`;
    const noteLines = task.notes.split("\n");
    noteLines.forEach((line) => {
      body += `  > ${line.trim()}
`;
    });
  }
  if (task.checklist && task.checklist.length > 0) {
    task.checklist.forEach((item) => {
      const itemCheckbox = item.completed ? "[x]" : "[ ]";
      body += `  + ${itemCheckbox} ${item.text}
`;
    });
  }
  let inlineFields = "";
  if (task.id) inlineFields += `[id:: ${task.id}] `;
  if (task.priority) {
    let priorityStr = "medium";
    if (task.priority === 0.1) priorityStr = "trivial";
    if (task.priority === 1) priorityStr = "low";
    if (task.priority === 1.5) priorityStr = "medium";
    if (task.priority === 2) priorityStr = "high";
    inlineFields += `[priority:: ${priorityStr}] `;
  }
  if (task.attribute) inlineFields += `[attribute:: ${task.attribute}] `;
  if (task.type === "daily" && task.frequency) inlineFields += `[frequency:: ${task.frequency}] `;
  if (task.type === "todo" && task.due) inlineFields += `[due:: ${task.due}] `;
  if (task.type === "habit") {
    if (task.up !== void 0) inlineFields += `[up:: ${task.up}] `;
    if (task.down !== void 0) inlineFields += `[down:: ${task.down}] `;
  }
  if (task.type === "reward" && task.value) {
    inlineFields += `[value:: ${task.value}] `;
  }
  if (inlineFields.trim()) {
    body += `
  ${inlineFields.trim()}
`;
  }
  if (body) {
    text += "\n" + body;
  }
  return text.trimEnd();
}

// src/sync/sync-manager.ts
var SyncManager = class {
  constructor(vault, pluginDir, apiClient, onConflict) {
    __publicField(this, "vault", vault);
    __publicField(this, "jsonStore");
    __publicField(this, "apiClient");
    __publicField(this, "queue");
    __publicField(this, "diffEngine");
    this.jsonStore = new JsonStore(vault.adapter, pluginDir);
    this.apiClient = apiClient;
    this.queue = new ActionQueue();
    this.diffEngine = new DiffEngine(this.apiClient, this.queue, onConflict);
  }
  /**
   * Executes the full ETL sync process.
   */
  async sync(markdownFile) {
    const remoteTasksList = await this.apiClient.fetchAllTasks();
    const remoteState = {};
    for (const task of remoteTasksList) {
      remoteState[task._id || task.id] = task;
    }
    const localStateObj = await this.jsonStore.loadAll();
    const localState = {};
    for (const list of Object.values(localStateObj)) {
      for (const task of list) {
        localState[task._id || task.id] = task;
      }
    }
    const content = await this.vault.read(markdownFile);
    const parsedMdState = parseMarkdown(content);
    const resolvedHabits = await this.diffEngine.resolve(
      localState,
      remoteState,
      parsedMdState.habits
    );
    const resolvedDailies = await this.diffEngine.resolve(
      localState,
      remoteState,
      parsedMdState.dailies
    );
    const resolvedTodos = await this.diffEngine.resolve(
      localState,
      remoteState,
      parsedMdState.todos
    );
    const resolvedRewards = await this.diffEngine.resolve(
      localState,
      remoteState,
      parsedMdState.rewards
    );
    const updatedLocalJsonObj = {
      habit: Object.values(resolvedHabits.updatedRemoteState).filter((t) => t.type === "habit"),
      daily: Object.values(resolvedDailies.updatedRemoteState).filter((t) => t.type === "daily"),
      todo: Object.values(resolvedTodos.updatedRemoteState).filter((t) => t.type === "todo"),
      reward: Object.values(resolvedRewards.updatedRemoteState).filter((t) => t.type === "reward")
    };
    await this.jsonStore.saveAll(updatedLocalJsonObj);
    const finalMdState = {
      habits: resolvedHabits.finalizedMarkdownTasks,
      dailies: resolvedDailies.finalizedMarkdownTasks,
      todos: resolvedTodos.finalizedMarkdownTasks,
      rewards: resolvedRewards.finalizedMarkdownTasks
    };
    const newMarkdown = generateMarkdown(finalMdState);
    await this.vault.modify(markdownFile, newMarkdown);
  }
};

// src/sync/conflict-modal.ts
var import_obsidian3 = require("obsidian");
var ConflictModal = class extends import_obsidian3.Modal {
  constructor(app, localTask, remoteTask, resolve) {
    super(app);
    __publicField(this, "localTask");
    __publicField(this, "remoteTask");
    __publicField(this, "resolvePromise");
    this.localTask = localTask;
    this.remoteTask = remoteTask;
    this.resolvePromise = resolve;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText("Sync conflict detected");
    contentEl.createEl("p", {
      text: `A conflict was detected for task: "${this.localTask.text || this.remoteTask.text}"`
    });
    contentEl.createEl("p", {
      text: "Both the local markdown and the remote Habitica API have changed since the last sync. Which version should take precedence?"
    });
    new import_obsidian3.Setting(contentEl).setName("Markdown version").setDesc("Keep your local changes and push them to Habitica.").addButton((btn) => btn.setButtonText("Choose markdown").setCta().onClick(() => {
      this.resolvePromise("markdown");
      this.close();
    }));
    new import_obsidian3.Setting(contentEl).setName("API version").setDesc("Keep the remote changes and overwrite your local markdown.").addButton((btn) => btn.setButtonText("Choose API").onClick(() => {
      this.resolvePromise("api");
      this.close();
    }));
    new import_obsidian3.Setting(contentEl).setName("Skip").setDesc("Do not sync this task right now.").addButton((btn) => btn.setButtonText("Skip").onClick(() => {
      this.resolvePromise("skip");
      this.close();
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
function promptConflictResolution(app, localTask, remoteTask) {
  return new Promise((resolve) => {
    const modal = new ConflictModal(app, localTask, remoteTask, resolve);
    modal.open();
  });
}

// src/main.ts
var HabiticaSyncPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    /** The global plugin settings */
    __publicField(this, "pluginSettings");
    /** The API client for communicating with Habitica */
    __publicField(this, "apiClient");
    /** The manager orchestrating the sync between Markdown and Habitica */
    __publicField(this, "syncManager");
  }
  /**
   * Called when the plugin is loaded by Obsidian.
   */
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new HabiticaSyncSettingTab(this.app, this));
    this.apiClient = new HabiticaApiClient({
      userId: this.pluginSettings.userId,
      apiToken: ""
      // Token fetched dynamically during sync
    });
    this.syncManager = new SyncManager(
      this.app.vault,
      `${this.app.vault.configDir}/plugins/${this.manifest.id}`,
      this.apiClient,
      (local, remote) => promptConflictResolution(this.app, local, remote)
    );
    this.addRibbonIcon("refresh-cw", "Sync Habitica tasks", async () => {
      await this.performSync();
    });
    this.addCommand({
      id: "sync-habitica-tasks",
      name: "Sync Habitica tasks",
      callback: async () => {
        await this.performSync();
      }
    });
  }
  /**
   * Called when the plugin is unloaded.
   */
  onunload() {
  }
  /**
   * Loads settings from the vault's data.json file.
   */
  async loadSettings() {
    const data = await this.loadData();
    this.pluginSettings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  /**
   * Saves settings to the vault's data.json file.
   */
  async saveSettings() {
    await this.saveData(this.pluginSettings);
  }
  /**
   * Fetches the API token securely and instantiates a new ApiClient.
   * @returns A boolean indicating success or failure.
   */
  async prepareApiClient() {
    var _a;
    if (!this.pluginSettings.userId || !this.pluginSettings.apiTokenSecretName) {
      new import_obsidian4.Notice("Habitica sync: Please configure your user ID and API token in settings.");
      return false;
    }
    try {
      const appSecret = this.app;
      const token = await ((_a = appSecret.secretStorage) == null ? void 0 : _a.getSecret(this.pluginSettings.apiTokenSecretName));
      if (!token) {
        new import_obsidian4.Notice("Habitica sync: API token is empty or missing from SecretStorage. Please set it in settings.");
        return false;
      }
      this.apiClient = new HabiticaApiClient({
        userId: this.pluginSettings.userId,
        apiToken: token
      });
      this.syncManager = new SyncManager(
        this.app.vault,
        `${this.app.vault.configDir}/plugins/${this.manifest.id}`,
        this.apiClient,
        (local, remote) => promptConflictResolution(this.app, local, remote)
      );
      return true;
    } catch (e) {
      new import_obsidian4.Notice("Habitica sync: Failed to read API token from SecretStorage.");
      return false;
    }
  }
  /**
   * Orchestrates the task synchronization process.
   */
  async performSync() {
    const isPrepared = await this.prepareApiClient();
    if (!isPrepared) return;
    const syncFilePath = this.pluginSettings.syncFilePath;
    let file = this.app.vault.getAbstractFileByPath(syncFilePath);
    if (!file || !(file instanceof import_obsidian4.TFile)) {
      try {
        const parts = syncFilePath.split("/");
        let currentPath = "";
        for (let i = 0; i < parts.length - 1; i++) {
          currentPath += parts[i] + "/";
          const folder = this.app.vault.getAbstractFileByPath(currentPath.slice(0, -1));
          if (!folder) {
            await this.app.vault.createFolder(currentPath.slice(0, -1));
          }
        }
        file = await this.app.vault.create(syncFilePath, "# Habitica Sync\n\n");
        new import_obsidian4.Notice(`Created new sync file at ${syncFilePath}`);
      } catch (err) {
        console.error(err);
        new import_obsidian4.Notice(`Failed to create sync file at ${syncFilePath}`);
        return;
      }
    }
    if (file instanceof import_obsidian4.TFile) {
      try {
        new import_obsidian4.Notice("Habitica sync started...");
        await this.syncManager.sync(file);
        new import_obsidian4.Notice("Habitica sync complete!");
      } catch (error) {
        console.error(error);
        if (error instanceof Error) {
          new import_obsidian4.Notice(`Habitica Sync Failed: ${error.message}`);
        } else {
          new import_obsidian4.Notice("Habitica sync failed with unknown error.");
        }
      }
    }
  }
};
